---
parent: plivosdk
serviceName: websdk
dockerOnly: false
language: nodejs
sonar:
  exclusions: node_modules/
unitTests:
  ignoreFailure: 'false'
  nodejs:
        testsReportFile: nodejs.tests.report.xml
        coverageReportFile: nodejs.coverage.report.xml
        command: |
          npm install
          npm run test:unit-jenkins
build:
  nodejs:
    command: npm install && npm run build
    outputDistDir: dist
